spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_tracking_dev
    username: student_tracking
    password: student_tracking_dev_password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
  jpa:
    show-sql: true

logging:
  level:
    com.student_tracking: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
